spring.application.name=Blanko
spring.datasource.url=jdbc:mysql://localhost:3306/blanko
spring.datasource.username=root
spring.datasource.password=coffee_cup1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true